name: deploy files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Compress action step
      run: cd dist; zip -r ../dist.zip *; cd ..
    - name: Deploy using curl POST
      run: curl -X POST ${{ secrets.DEPLOY_URL }} -T dist.zip