name: deploy files
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Compress action step
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: ./
        files: |
            ./dist/*
        outPath: dist.tar.gz
    - name: Deploy using curl POST
      run: curl -X POST ${{ secrets.DEPLOY_URL }} -T dist.tar.gz